# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Card.create(rank: "A", suit: "♣", value: 14, color: 'black')
Card.create(rank: "A", suit: "♠", value: 14, color: 'black')
Card.create(rank: "A", suit: "♡", value: 14, color: 'red')
Card.create(rank: "A", suit: "♢", value: 14, color: 'red')
Card.create(rank: "2", suit: "♣", value: 2, color: 'black')
Card.create(rank: "2", suit: "♠", value: 2, color: 'black')
Card.create(rank: "2", suit: "♡", value: 2, color: 'red')
Card.create(rank: "2", suit: "♢", value: 2, color: 'red')
Card.create(rank: "3", suit: "♣", value: 3, color: 'black')
Card.create(rank: "3", suit: "♠", value: 3, color: 'black')
Card.create(rank: "3", suit: "♡", value: 3, color: 'red')
Card.create(rank: "3", suit: "♢", value: 3, color: 'red')
Card.create(rank: "4", suit: "♣", value: 4, color: 'black')
Card.create(rank: "4", suit: "♠", value: 4, color: 'black')
Card.create(rank: "4", suit: "♡", value: 4, color: 'red')
Card.create(rank: "4", suit: "♢", value: 4, color: 'red')
Card.create(rank: "5", suit: "♣", value: 5, color: 'black')
Card.create(rank: "5", suit: "♠", value: 5, color: 'black')
Card.create(rank: "5", suit: "♡", value: 5, color: 'red')
Card.create(rank: "5", suit: "♢", value: 5, color: 'red')
Card.create(rank: "6", suit: "♣", value: 6, color: 'black')
Card.create(rank: "6", suit: "♠", value: 6, color: 'black')
Card.create(rank: "6", suit: "♡", value: 6, color: 'red')
Card.create(rank: "6", suit: "♢", value: 6, color: 'red')
Card.create(rank: "7", suit: "♣", value: 7, color: 'black')
Card.create(rank: "7", suit: "♠", value: 7, color: 'black')
Card.create(rank: "7", suit: "♡", value: 7, color: 'red')
Card.create(rank: "7", suit: "♢", value: 7, color: 'red')
Card.create(rank: "8", suit: "♣", value: 8, color: 'black')
Card.create(rank: "8", suit: "♠", value: 8, color: 'black')
Card.create(rank: "8", suit: "♡", value: 8, color: 'red')
Card.create(rank: "8", suit: "♢", value: 8, color: 'red')
Card.create(rank: "9", suit: "♣", value: 9, color: 'black')
Card.create(rank: "9", suit: "♠", value: 9, color: 'black')
Card.create(rank: "9", suit: "♡", value: 9, color: 'red')
Card.create(rank: "9", suit: "♢", value: 9, color: 'red')
Card.create(rank: "10", suit: "♣", value: 10, color: 'black')
Card.create(rank: "10", suit: "♠", value: 10, color: 'black')
Card.create(rank: "10", suit: "♡", value: 10, color: 'black')
Card.create(rank: "10", suit: "♢", value: 10, color: 'black')
Card.create(rank: "J", suit: "♣", value: 11, color: 'black')
Card.create(rank: "J", suit: "♠", value: 11, color: 'black')
Card.create(rank: "J", suit: "♡", value: 11, color: 'black')
Card.create(rank: "J", suit: "♢", value: 11, color: 'black')
Card.create(rank: "Q", suit: "♣", value: 12, color: 'black')
Card.create(rank: "Q", suit: "♠", value: 12, color: 'black')
Card.create(rank: "Q", suit: "♡", value: 12, color: 'black')
Card.create(rank: "Q", suit: "♢", value: 12, color: 'black')
Card.create(rank: "K", suit: "♣", value: 13, color: 'black')
Card.create(rank: "K", suit: "♠", value: 13, color: 'black')
Card.create(rank: "K", suit: "♡", value: 13, color: 'black')
Card.create(rank: "K", suit: "♢", value: 13, color: 'black')

